### PR TITLE
feat: allow Assume Role

### PR DESCRIPTION
**Pull request by elliottohara**
Address https://github.com/moritzzimmer/terraform-aws-lambda/issues/108

### CODE REVIEW

**Comment by moritzzimmer** [comment]
thx for this PR @elliottohara. What kind of modifications do you need for the default policy? Maybe we can provide variables to costomize those use cases instead of overriding in total?

**Comment by elliottohara** [comment]
I need to invoke the lambda cross account from another lambda. Granting
sts:AssumeRole to an IAM role in another account.

I thought about adding more customization, but felt like that would be
significantly harder to maintain long term as more customized needs came
up. This way, we can rely on the intelligent defaults provided, but if
someone knows they need something else, it’s their responsibility to
provide the override.

**Comment by elliottohara** [comment]
This is how I'm using it.

```

data "aws_iam_policy_document" "command-handler-assume-role-policy" {
  statement {
    actions = ["sts:AssumeRole"]

    principals {
      type        = "AWS"
      identifiers = [module.command_handler_service.value.retool_command_handler.role.arn]
    }
  }
}

module "command-handler-lambda" {
  source             = "..."
  assume_role_policy = data.aws_iam_policy_document.configure-giftcard-site-handler-assume-role-policy.json
  .. other stuff 
    }
  }
}


``` 
This also means that we have to grant `lambda:InvokeFunction` to the role, which we do the same way we attach any other permissions to the role. 

I'd be concerned about adding all that to this module as I'm afraid that would make it more brittle, and frankly, our use case (x account lambda invocation) isn't standard. In fact, I'm told our team it's a "mild" antipattern. I'd much rather use API gatweway for this.

**Comment by moritzzimmer** [comment]
Would this proposal work for your use case?

```hcl
// variables.tf
variable "trusted_entities" {
  description = "Additional trusted entities allowed to assume the Lambda execution role."
  default     = []
  type = list(object({
    type        = string
    identifiers = list(string)
  }))
}

// iam.tf
locals {
trusted_services = distinct(flatten(concat(
    slice(["lambda.amazonaws.com", "edgelambda.amazonaws.com"], 0, var.lambda_at_edge ? 2 : 1),
    [for entity in var.trusted_entities : entity.identifiers if entity.type == "Service"]))
  )
}

data "aws_iam_policy_document" "assume_role_policy" {
  statement {
    actions = ["sts:AssumeRole"]

    // default trust service relationships
    principals {
      type        = "Service"
      identifiers = local.trusted_services
    }

    dynamic "principals" {
      for_each = [for entity in var.trusted_entities : entity if entity.type != "Service"]
      content {
        type        = principals.value.type
        identifiers = principals.value.identifiers
      }
    }
  }
}
```

This way we could keep the default trust relationships for Lambda and Lambda@Edge as well as supporting additional `Service` and `AWS` types of principals.

**Comment by elliottohara** [comment]
I mean, well, the code would execute, but it's not what I want, because I don't want "additional" trusted entities. I want to trust only the principals I specify. 

The only reason I'd need to trust the lambda or lambda@edge service is if I want AWS to assume the role when it invokes a lambda (because of some triggering mechanism). Since this lambda will always only be invoked via actual lambda invoke function calls from some other code, granting the privilege to the service violates PLP. 

If the code you mentioned wasn't "additional" and instead was "override" or something, I'd love it.

**Comment by moritzzimmer** [comment]
@elliottohara thanks for the explanation - awesome to hear about your usage of this module!

I was wondering if attaching a [resource-based policy](https://docs.aws.amazon.com/lambda/latest/dg/access-control-resource-based.html#permissions-resource-xaccountinvoke) to the target Lambda function allowing the source account id would be sufficient in that case?

I was just playing around with a simple example:

```hcl
resource "aws_lambda_permission" "cross_account_invoke" {
  statement_id  = "AllowExecutionFromCrossAccountLambda"
  action        = "lambda:InvokeFunction"
  function_name = module.lambda.function_name // target function name
  principal     = "12345678912" // source account ID 
}
```

Example function calling the one with the attached permission above:

```python
def lambda_handler(event, context):
  lambda_client = boto3.client('lambda', region_name='eu-west-1')

  # Specify the parameters for invoking the target Lambda function
  params = {
    'FunctionName': 'arn:aws:lambda:eu-west-1:10987654321:function:target-function-name',
    'InvocationType': 'Event',  # or 'Event' for asynchronous invocation
    'LogType': 'Tail',
    'Payload': json.dumps({'key': 'value'}),  # Your input payload
  }

# other code omitted
```

Don't want to block things here, just trying to keep things as simple as possible.

**Pull request closed without merging**
